M48
; DRILL file {KiCad (6.0.6)} date Sun 26 Jun 2022 02:31:42 AM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-26T02:31:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.5692Y-2.8209
X7.5692Y-3.0118
T2
X7.6885Y-2.8091
X7.6885Y-3.0236
T0
M30
