M48
; DRILL file {KiCad 7.0.8} date Mon 30 Oct 2023 08:32:04 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-30T20:32:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.5692Y-2.8209
X7.5692Y-3.0118
T2
X7.6885Y-2.8091
X7.6885Y-3.0236
T0
M30
