name: Build
on:
  push:
    branches:
      - main
      - develop
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}"
        mkdir -p "${{ github.workspace }}"

    - name: Checkout PicoCart64
      uses: actions/checkout@v2
      with:
        path: picocart64

    - name: Check for bad indentation
      run: |
        sudo apt-get install -y indent git
        ./picocart64/sw/scripts/indent.sh -c

    - name: Check for modified files (indent changed) verbose
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.head_ref }}
        echo ${{ github.event.pull_request.head.repo.full_name }}
        git -C picocart64 status;
        git -C picocart64 branch;
        git -C picocart64 remote -v;
        git -C picocart64 diff-index HEAD --;

    - name: Check for modified files (indent changed)
      id: git-check
      run: echo ::set-output name=modified::$(if git -C picocart64 diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'GitHub CI'
        git config --global user.email 'kbeckmann@users.noreply.github.com'
        git -C picocart64 remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git -C picocart64 commit -am "Automated changes"
        git -C picocart64 push
